/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Apr 24, 2011, 10:09:44 AM
 */

package distribuidos.gui;
import distribuidos.datos.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author CZH
 */
public class MainWindow extends javax.swing.JFrame {
  //  private DaoSupermercadoXml datosTam = new DaoSupermercadoXml();
    /** Creates new form MainWindow */
    
   
    public MainWindow() {
        
        
        initComponents();
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
        
    
        
        setDefaultCloseOperation (WindowConstants.DO_NOTHING_ON_CLOSE);

addWindowListener(new WindowAdapter(){
    public void windowClosing(WindowEvent we){
       
            System.exit(0);
    }
});
      
          

      
      
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMIManejoPedidos = new javax.swing.JLabel();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMIActualizar = new javax.swing.JMenuItem();
        jMIExit = new javax.swing.JMenuItem();
        jMGestion = new javax.swing.JMenu();
        jMProductos = new javax.swing.JMenu();
        jMIManejoProducto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Supermercado");
        setName("Supermercado"); // NOI18N
        setResizable(false);

        jMIManejoPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/430x460.jpg"))); // NOI18N

        jMBPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jMenu2.setText("Sistema");
        jMenu2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jMIActualizar.setText("Actualizar");
        jMIActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIActualizarActionPerformed(evt);
            }
        });
        jMenu2.add(jMIActualizar);

        jMIExit.setText("Exit");
        jMIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExitActionPerformed(evt);
            }
        });
        jMenu2.add(jMIExit);

        jMBPrincipal.add(jMenu2);

        jMGestion.setText("Gestión");
        jMGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionActionPerformed(evt);
            }
        });

        jMProductos.setText("Productos");

        jMIManejoProducto.setText("Manejo");
        jMIManejoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoProductoActionPerformed(evt);
            }
        });
        jMProductos.add(jMIManejoProducto);

        jMGestion.add(jMProductos);

        jMenu1.setText("Ventas");

        jMenuItem1.setText("Ventas de Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMGestion.add(jMenu1);

        jMenu3.setText("Pedidos");

        jMenuItem2.setText("Agregar Pedido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Manejo Pedido");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMGestion.add(jMenu3);

        jMBPrincipal.add(jMGestion);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMIManejoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMIManejoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-421)/2, (screenSize.height-451)/2, 421, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExitActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jMIExitActionPerformed

    
    
    private void jMIManejoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoProductoActionPerformed
        // TODO add your handling code here:
              XMLnodos xmlnodo = new XMLnodos();
          int var=0;
          for (int i = 0; i < xmlnodo.cantNodos(); i++) {
           
              var=xmlnodo.cargaArchivos(i);
              Hilo Hilo;
              // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
            if(var==1){
             
               Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
               Hilo.start();
               
            }

    
       }   
        
        ManejoProducto elip = new ManejoProducto();
    elip.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_jMIManejoProductoActionPerformed

    private void jMIActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIActualizarActionPerformed
     XMLnodos xmlnodo = new XMLnodos();
          int var=0;
          for (int i = 0; i < xmlnodo.cantNodos(); i++) {
           
              var=xmlnodo.cargaArchivos(i);
              Hilo Hilo;
              // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
            if(var==1){
                //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
             
                //Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion) {
               Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
               Hilo.start();
               
            }

      // TODO add your handling code here:
       }        // TODO add your handling code here:
          
         

       
    }//GEN-LAST:event_jMIActualizarActionPerformed

    private void jMGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionActionPerformed
       
          
    }//GEN-LAST:event_jMGestionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                   XMLnodos xmlnodo = new XMLnodos();
          int var=0;
          for (int i = 0; i < xmlnodo.cantNodos(); i++) {
           
              var=xmlnodo.cargaArchivos(i);
              Hilo Hilo;
              // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
            if(var==1){
             
               Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
               Hilo.start();
               
            }

    
       }   
        
        VentaProducto elip = new VentaProducto();
         elip.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         ManejoPedido elip = new ManejoPedido();
         elip.setVisible(true);
         this.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         EditarPedido elip = new EditarPedido();
         elip.setVisible(true);
         this.setEnabled(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMGestion;
    private javax.swing.JMenuItem jMIActualizar;
    private javax.swing.JMenuItem jMIExit;
    private javax.swing.JLabel jMIManejoPedidos;
    private javax.swing.JMenuItem jMIManejoProducto;
    private javax.swing.JMenu jMProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

}
