/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearProducto.java
 *
 * Created on 24/04/2011, 12:32:08 PM
 */
package distribuidos.gui;
import distribuidos.datos.ManejoXMLProducto;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import distribuidos.datos.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class ManejoPedido extends javax.swing.JFrame {

    
    private ManejoXMLProducto xmlproducto = new ManejoXMLProducto();
    private Util util = new Util();
    private List<Pedido> lista = new ArrayList<Pedido>();
    /** Creates new form CrearProducto */
    public ManejoPedido() {
        initComponents();
        initMyOwnComponents();
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPFondo = new javax.swing.JLayeredPane();
        jBSeleccionar = new javax.swing.JButton();
        jBPedir = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLProducto = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTFCantidadV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Producto");
        setResizable(false);

        jLPFondo.setBackground(new java.awt.Color(255, 255, 255));

        jBSeleccionar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBSeleccionar.setText("Seleccionar");
        jBSeleccionar.setVerifyInputWhenFocusTarget(false);
        jBSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeleccionarActionPerformed(evt);
            }
        });
        jBSeleccionar.setBounds(210, 100, 100, 20);
        jLPFondo.add(jBSeleccionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBPedir.setText("Pedir");
        jBPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPedirActionPerformed(evt);
            }
        });
        jBPedir.setBounds(210, 300, 90, 23);
        jLPFondo.add(jBPedir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre:");
        jLNombre.setBounds(10, 70, 60, 14);
        jLPFondo.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFNombre.setEditable(false);
        jTFNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.setBounds(140, 70, 150, 20);
        jLPFondo.add(jTFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLProducto.setText("Producto:");
        jLProducto.setBounds(10, 40, 110, 14);
        jLPFondo.add(jLProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });
        jCBProducto.setBounds(140, 40, 150, 20);
        jLPFondo.add(jCBProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad a Pedir:");
        jLabel1.setBounds(10, 100, 120, 14);
        jLPFondo.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTFCantidadV.setBounds(140, 100, 50, 20);
        jLPFondo.add(jTFCantidadV, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(40, 150, 452, 130);
        jLPFondo.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/561x571.jpg"))); // NOI18N
        jLFondo.setBounds(0, -170, 560, 530);
        jLPFondo.add(jLFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-554)/2, (screenSize.height-377)/2, 554, 377);
    }// </editor-fold>//GEN-END:initComponents
  
    private void jBSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeleccionarActionPerformed
       Comunicacion com = new Comunicacion();
       int sucursal = Util.getId();
       int i;
       String[] idProducto1 = jCBProducto.getSelectedItem().toString().split(" ");
    
          //  Comunicacion com = new Comunicacion();
        List<Pedido> lista2 = new ArrayList<Pedido>();
        Pedido registrar = new  Pedido(Integer.toString(sucursal),idProducto1[0],jTFNombre.getText(),jTFCantidadV.getText(),"pendiente","Sin observacion");
        lista.add(registrar);
        lista2.add(registrar);
        registrar.setLista(lista);
          for (i=0; i<lista2.size(); i++){
            
                ((DefaultTableModel) this.jTable1.getModel()).addRow(new Object[]{lista2.get(i).getNombreProducto(),lista2.get(i).getCantidad(),lista2.get(i).getEstatus()});
//                   System.out.println("NOMBRE:  "+ registrar.getLista().get(i).getNombreProducto());
//               System.out.println("Cantidad:  "+ registrar.getLista().get(i).getCantidad());
            }
      
       jTFCantidadV.setText(" ");
       jTFNombre.setText(" ");
//            
//        
//        
       
      //  com.pedidos(Integer.toString(sucursal), jCBProducto.getSelectedItem(), jTFNombre.getText() ,jTFCantidadV.getText(),"pendiente");
       // this.dispose();
    }//GEN-LAST:event_jBSeleccionarActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
     if (jCBProducto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un Producto","Error", JOptionPane.ERROR_MESSAGE);
     }
     else{
         xmlproducto.cargarInformacion(jCBProducto.getSelectedItem(),jTFNombre);

     }
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jBPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPedirActionPerformed
       Comunicacion com = new Comunicacion();
      // Pedido ped = new Pedido();
      
       int i;
  //    List<Pedido> lista = new ArrayList<Pedido>();
       // Pedido registrar = new  Pedido(Integer.toString(sucursal),idProducto1[0],jTFNombre.getText(),jTFCantidadV.getText(),"pendiente"," ");
      lista=distribuidos.datos.Pedido.getLista();
     
        for (i=0; i<lista.size(); i++){
         com.nuevoPedido(distribuidos.datos.Pedido.getLista().get(i).getIdSuper(), distribuidos.datos.Pedido.getLista().get(i).getIdProducto(), distribuidos.datos.Pedido.getLista().get(i).getNombreProducto(), distribuidos.datos.Pedido.getLista().get(i).getCantidad(), distribuidos.datos.Pedido.getLista().get(i).getEstatus(), distribuidos.datos.Pedido.getLista().get(i).getObservacion());   

            }
        this.dispose();
     // com.pedidos(ped.getLista());
    }//GEN-LAST:event_jBPedirActionPerformed
                   
    /**
     * @param args the command line arguments
     */
            private void initMyOwnComponents()
    {
            xmlproducto.cargarListaProductoEnCombo(this.jCBProducto, false);
//              Utilitaria.cargarListaAlmacenajeEnCombo(jCBAlmacenaje, false);
    }
    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
        
            public void run() {
                new ManejoPedido().setVisible(true);
            }
        });
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPedir;
    private javax.swing.JButton jBSeleccionar;
    private javax.swing.JComboBox jCBProducto;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLayeredPane jLPFondo;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidadV;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
