/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearProducto.java
 *
 * Created on 24/04/2011, 12:32:08 PM
 */
package distribuidos.gui;
import distribuidos.datos.*;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ManejoProducto extends javax.swing.JFrame {

    
    private ManejoXMLProducto xmlproducto = new ManejoXMLProducto();
    private Util util = new Util();
    /** Creates new form CrearProducto */
    public ManejoProducto() {
        initComponents();
        initMyOwnComponents();
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPFondo = new javax.swing.JLayeredPane();
        jTFCodigo = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jLCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jLPvp = new javax.swing.JLabel();
        jTFPvp = new javax.swing.JTextField();
        jLImagen = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jTFStockMin = new javax.swing.JTextField();
        jLStrockMin = new javax.swing.JLabel();
        jBAtras = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLImagenPro = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jLProducto = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Producto");
        setResizable(false);

        jLPFondo.setBackground(new java.awt.Color(255, 255, 255));

        jTFCodigo.setEditable(false);
        jTFCodigo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoActionPerformed(evt);
            }
        });
        jTFCodigo.setBounds(380, 30, 150, 20);
        jLPFondo.add(jTFCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCodigo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLCodigo.setText("Codigo:");
        jLCodigo.setBounds(280, 30, 60, 20);
        jLPFondo.add(jLCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLDescripcion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLDescripcion.setText("Descripcion:");
        jLDescripcion.setBounds(280, 90, 70, 20);
        jLPFondo.add(jLDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFDescripcion.setEditable(false);
        jTFDescripcion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescripcionActionPerformed(evt);
            }
        });
        jTFDescripcion.setBounds(380, 90, 150, 20);
        jLPFondo.add(jTFDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLCantidad.setText("Cantidad:");
        jLCantidad.setBounds(280, 150, 70, 20);
        jLPFondo.add(jLCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantidadActionPerformed(evt);
            }
        });
        jTFCantidad.setBounds(380, 150, 150, 20);
        jLPFondo.add(jTFCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLPvp.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLPvp.setForeground(new java.awt.Color(255, 255, 255));
        jLPvp.setText("Precio:");
        jLPvp.setBounds(280, 180, 70, 20);
        jLPFondo.add(jLPvp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFPvp.setEditable(false);
        jTFPvp.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFPvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPvpActionPerformed(evt);
            }
        });
        jTFPvp.setBounds(380, 180, 150, 20);
        jLPFondo.add(jTFPvp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLImagen.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLImagen.setForeground(new java.awt.Color(255, 255, 255));
        jLImagen.setText("Imagen:");
        jLImagen.setBounds(20, 80, 70, 14);
        jLPFondo.add(jLImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBSalir.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBSalir.setText("Modificar");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jBSalir.setBounds(40, 310, 90, 20);
        jLPFondo.add(jBSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFStockMin.setEditable(false);
        jTFStockMin.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFStockMinActionPerformed(evt);
            }
        });
        jTFStockMin.setBounds(380, 120, 150, 20);
        jLPFondo.add(jTFStockMin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLStrockMin.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLStrockMin.setForeground(new java.awt.Color(255, 255, 255));
        jLStrockMin.setText("Estado:");
        jLStrockMin.setBounds(280, 120, 90, 20);
        jLPFondo.add(jLStrockMin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBAtras.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBAtras.setText("Aceptar");
        jBAtras.setVerifyInputWhenFocusTarget(false);
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        jBAtras.setBounds(430, 310, 80, 20);
        jLPFondo.add(jBAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre:");
        jLNombre.setBounds(280, 60, 60, 20);
        jLPFondo.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFNombre.setEditable(false);
        jTFNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.setBounds(380, 60, 150, 20);
        jLPFondo.add(jTFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLImagenPro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLImagenPro.setBounds(140, 80, 110, 130);
        jLPFondo.add(jLImagenPro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jBEliminar.setBounds(230, 310, 100, 23);
        jLPFondo.add(jBEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLProducto.setText("Producto:");
        jLProducto.setBounds(20, 30, 110, 14);
        jLPFondo.add(jLProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });
        jCBProducto.setBounds(120, 30, 130, 20);
        jLPFondo.add(jCBProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/561x571.jpg"))); // NOI18N
        jLFondo.setBounds(0, -230, 560, 570);
        jLPFondo.add(jLFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-554)/2, (screenSize.height-377)/2, 554, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jTFCodigoActionPerformed
  
    private void jTFStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFStockMinActionPerformed

    private void jTFDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescripcionActionPerformed

    private void jTFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantidadActionPerformed

    private void jTFPvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPvpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPvpActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        
         int num =0;
            num=Util.ValidarEntero(jTFCantidad.getText(), "Cantidad debe ser un numero");
            if (jCBProducto.getSelectedIndex()==0||num==0){
            JOptionPane.showMessageDialog(null,"Indique opcion correcta","Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
           XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                
                //  public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String idProducto, String cantidadProducto1)
                 
                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"modificar", jTFCodigo.getText(),jTFCantidad.getText());
                Hilo.start();
             }
            xmlproducto.updateProductoSucursal(jTFCodigo.getText(),jTFCantidad.getText());

       // TODO add your handling code here:
        }
            }
   this.dispose();
        
        
        
        
        
         
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if (jCBProducto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debe seleccionar una opcion ","Error", JOptionPane.ERROR_MESSAGE);
        }else{
              XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                
                //  Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String idProducto)
                 
                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"modificarEstado", jTFCodigo.getText());
                Hilo.start();
             }
            xmlproducto.borrarProducto(jTFCodigo.getText());
            
           }
                //funcion.eliminarProducto(jCBSupermercado.getSelectedIndex()-1, jCBSucursal.getSelectedIndex()-1,jCBProducto.getSelectedIndex()-1);
        this.dispose();}
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
         if (jCBProducto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un Producto","Error", JOptionPane.ERROR_MESSAGE);
     }
     else{  
      xmlproducto.cargarInformacionProducto(jCBProducto.getSelectedItem(), jTFCodigo, jTFNombre, jTFDescripcion,jTFCantidad,  jTFPvp,jLImagenPro,jTFStockMin);
     }
    }//GEN-LAST:event_jCBProductoActionPerformed
                   
    /**
     * @param args the command line arguments
     */
            private void initMyOwnComponents()
    {
            xmlproducto.cargarListaProductoEnCombo(this.jCBProducto, false);
//              Utilitaria.cargarListaAlmacenajeEnCombo(jCBAlmacenaje, false);
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManejoProducto().setVisible(true);
            }
        });
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox jCBProducto;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLImagenPro;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLayeredPane jLPFondo;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLPvp;
    private javax.swing.JLabel jLStrockMin;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPvp;
    private javax.swing.JTextField jTFStockMin;
    // End of variables declaration//GEN-END:variables
}
