/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Apr 24, 2011, 10:09:44 AM
 */

package distribuidos.gui;
import distribuidos.datos.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
/**
 *
 * @author CZH
 */
public class MainWindow extends javax.swing.JFrame {
  //  private DaoSupermercadoXml datosTam = new DaoSupermercadoXml();
    /** Creates new form MainWindow */
     private ManejoXMLProducto xmlproducto = new ManejoXMLProducto();
     
    public MainWindow() {
        
        initComponents();
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
 setDefaultCloseOperation (WindowConstants.DO_NOTHING_ON_CLOSE);

addWindowListener(new WindowAdapter(){
   public void windowClosing(WindowEvent we){
      
           System.exit(0);
   }
});
        XMLnodos xmlnodo = new XMLnodos();
           int var=0;
//           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
//            
//               var=xmlnodo.cargaArchivos(i);
//               Hilo Hilo;
//               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
//             if(var==1){
//                 //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
//              
//                 //Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion) {
//                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
//                Hilo.start();
//             }
//
//       // TODO add your handling code here:
//        }

        
         

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMIManejoPedidos = new javax.swing.JLabel();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMActualizar = new javax.swing.JMenuItem();
        jMIExit1 = new javax.swing.JMenuItem();
        jMGestion = new javax.swing.JMenu();
        jMProductos = new javax.swing.JMenu();
        jMIManejoProducto2 = new javax.swing.JMenuItem();
        jMIManejoProducto = new javax.swing.JMenuItem();
        jMProductos1 = new javax.swing.JMenu();
        jMIManejoProducto3 = new javax.swing.JMenuItem();
        jMIManejoProducto4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Supermercado");
        setName("Supermercado"); // NOI18N
        setResizable(false);

        jMIManejoPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/430x460.jpg"))); // NOI18N

        jMBPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jMenu2.setText("Sistema");
        jMenu2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jMActualizar.setText("Actualizar");
        jMActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMActualizarActionPerformed(evt);
            }
        });
        jMenu2.add(jMActualizar);

        jMIExit1.setText("Exit");
        jMIExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExit1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMIExit1);

        jMBPrincipal.add(jMenu2);

        jMGestion.setText("Gestión");
        jMGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionActionPerformed(evt);
            }
        });

        jMProductos.setText("Productos");

        jMIManejoProducto2.setText("Registrar");
        jMIManejoProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoProducto2ActionPerformed(evt);
            }
        });
        jMProductos.add(jMIManejoProducto2);

        jMIManejoProducto.setText("Manejo");
        jMIManejoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoProductoActionPerformed(evt);
            }
        });
        jMProductos.add(jMIManejoProducto);

        jMGestion.add(jMProductos);

        jMProductos1.setText("Sucursales");

        jMIManejoProducto3.setText("Consultar");
        jMIManejoProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoProducto3ActionPerformed(evt);
            }
        });
        jMProductos1.add(jMIManejoProducto3);

        jMIManejoProducto4.setText("Registrar");
        jMIManejoProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoProducto4ActionPerformed(evt);
            }
        });
        jMProductos1.add(jMIManejoProducto4);

        jMGestion.add(jMProductos1);

        jMenu1.setText("Ventas");

        jMenuItem1.setText("Reporte de Ventas ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMGestion.add(jMenu1);

        jMenu3.setText("Pedidos");

        jMenuItem2.setText("Manejo Pedido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMGestion.add(jMenu3);

        jMBPrincipal.add(jMGestion);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMIManejoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMIManejoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-421)/2, (screenSize.height-451)/2, 421, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void jMActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMActualizarActionPerformed
        // TODO add your handling code here:
           XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                 //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
              
                 //Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion) {
                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
                Hilo.start();
             }

       // TODO add your handling code here:
        }

     //   System.out.println("ready");
          
    }//GEN-LAST:event_jMActualizarActionPerformed

    private void jMIManejoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoProductoActionPerformed
        // TODO add your handling code here:
        ManejoProducto elip = new ManejoProducto();
    elip.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_jMIManejoProductoActionPerformed

    private void jMIManejoProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoProducto2ActionPerformed
        // TODO add your handling code here:
        
        RegistroProducto fran = new RegistroProducto();
        fran.setVisible(true);
        this.setEnabled(true); 
        
    }//GEN-LAST:event_jMIManejoProducto2ActionPerformed

    private void jMIManejoProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoProducto3ActionPerformed
         ConsultaSucursal fran = new ConsultaSucursal();
        fran.setVisible(true);
        this.setEnabled(true); 
    }//GEN-LAST:event_jMIManejoProducto3ActionPerformed

    private void jMIManejoProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoProducto4ActionPerformed
           RegistroSucursal fran = new RegistroSucursal();
        fran.setVisible(true);
        this.setEnabled(true); 
        
    }//GEN-LAST:event_jMIManejoProducto4ActionPerformed

    private void jMIExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMIExit1ActionPerformed

    private void jMGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionActionPerformed
        // TODO add your handling code here:
        XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                 //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
              
                 //Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion) {
                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"actualizarNuevo");
                Hilo.start();
             }

       // TODO add your handling code here:
        }

        
        
    }//GEN-LAST:event_jMGestionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
               XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                 //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
              
                 //Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion) {
                Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"webservice");
                Hilo.start();
             }

       // TODO add your handling code here:
        }
          ReporteVenta fran = new ReporteVenta();
        fran.setVisible(true);
        this.setEnabled(true); 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          ManejoPedido fran = new ManejoPedido();
        fran.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMActualizar;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMGestion;
    private javax.swing.JMenuItem jMIExit1;
    private javax.swing.JLabel jMIManejoPedidos;
    private javax.swing.JMenuItem jMIManejoProducto;
    private javax.swing.JMenuItem jMIManejoProducto2;
    private javax.swing.JMenuItem jMIManejoProducto3;
    private javax.swing.JMenuItem jMIManejoProducto4;
    private javax.swing.JMenu jMProductos;
    private javax.swing.JMenu jMProductos1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

}
