/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearProducto.java
 *
 * Created on 24/04/2011, 12:32:08 PM
 */
package distribuidos.gui;
import distribuidos.datos.*;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import webservice.Pedido;

/**
 *
 * @author Administrador
 */
public class ManejoPedido extends javax.swing.JFrame {

  //  private ManejoXMLProducto.agregarArchivo archi = new ManejoXMLProducto.;
    private ManejoXMLProducto xmlproducto = new ManejoXMLProducto();
     private ManejoXMLSupermercado xmlsuper = new ManejoXMLSupermercado();
    private Util util = new Util();
    private String nombrePro;

    /** Creates new form CrearProducto */
    public ManejoPedido() {
        initComponents();
        initMyOwnComponents();
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPFondo = new javax.swing.JLayeredPane();
        jLDescripcion = new javax.swing.JLabel();
        jLSupermercado = new javax.swing.JLabel();
        jCBSupermercado = new javax.swing.JComboBox();
        jTFObservacion = new javax.swing.JTextField();
        jLCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jLPvp = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLProducto = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Producto");
        setResizable(false);

        jLPFondo.setBackground(new java.awt.Color(255, 255, 255));

        jLDescripcion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLDescripcion.setText("Observacion:");
        jLDescripcion.setBounds(80, 190, 90, 20);
        jLPFondo.add(jLDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLSupermercado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLSupermercado.setForeground(new java.awt.Color(255, 255, 255));
        jLSupermercado.setText("Sucursal:");
        jLSupermercado.setBounds(90, 20, 110, 14);
        jLPFondo.add(jLSupermercado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBSupermercado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jCBSupermercado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jCBSupermercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSupermercadoActionPerformed(evt);
            }
        });
        jCBSupermercado.setBounds(190, 20, 130, 20);
        jLPFondo.add(jCBSupermercado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFObservacion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFObservacionActionPerformed(evt);
            }
        });
        jTFObservacion.setBounds(180, 190, 300, 20);
        jLPFondo.add(jTFObservacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLCantidad.setText("Cantidad:");
        jLCantidad.setBounds(80, 120, 70, 20);
        jLPFondo.add(jLCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantidadActionPerformed(evt);
            }
        });
        jTFCantidad.setBounds(180, 120, 150, 20);
        jLPFondo.add(jTFCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLPvp.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLPvp.setForeground(new java.awt.Color(255, 255, 255));
        jLPvp.setText("Estatus:");
        jLPvp.setBounds(80, 150, 70, 20);
        jLPFondo.add(jLPvp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBSalir.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBSalir.setText("Modificar");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jBSalir.setBounds(150, 310, 90, 20);
        jLPFondo.add(jBSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBAtras.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBAtras.setText("Aceptar");
        jBAtras.setVerifyInputWhenFocusTarget(false);
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        jBAtras.setBounds(310, 310, 80, 20);
        jLPFondo.add(jBAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre:");
        jLNombre.setBounds(80, 90, 60, 20);
        jLPFondo.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.setBounds(180, 90, 150, 20);
        jLPFondo.add(jTFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLProducto.setText("Pedido:");
        jLProducto.setBounds(90, 50, 110, 14);
        jLPFondo.add(jLProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBProducto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });
        jCBProducto.setBounds(190, 50, 130, 20);
        jLPFondo.add(jCBProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pendiente", "enviado", "cancelado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setBounds(180, 150, 140, 20);
        jLPFondo.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/561x571.jpg"))); // NOI18N
        jLFondo.setBounds(0, -230, 560, 570);
        jLPFondo.add(jLFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-554)/2, (screenSize.height-377)/2, 554, 377);
    }// </editor-fold>//GEN-END:initComponents
  
    private void jTFObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFObservacionActionPerformed

    private void jTFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantidadActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed

      xmlproducto.updatePedidoFranquicia(jCBSupermercado.getSelectedItem(),jCBProducto.getSelectedItem(),jTFCantidad.getText(), jComboBox1.getSelectedItem().toString(),jTFObservacion.getText());
      JOptionPane.showMessageDialog(null,"Se ha modificado el pedido","Aceptar", JOptionPane.OK_OPTION);
      jTFNombre.setText(" ");
      jTFCantidad.setText(" ");
      jTFObservacion.setText(" ");
     
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
       int i;
       Comunicacion com = new Comunicacion();
      List<distribuidos.datos.Pedido> lista =  xmlproducto.llenarPedidos();
        com.borrarXMLPedido();
      for (i=0; i<lista.size(); i++){
     
       com.nuevoPedido2(lista.get(i).getIdSuper(), lista.get(i).getIdProducto(), lista.get(i).getNombreProducto(), lista.get(i).getCantidad(), lista.get(i).getEstatus(), lista.get(i).getObservacion());   
             
            }
       this.dispose();
       
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
     if (jCBProducto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debe seleccionar una opcion en Supermercado","Error", JOptionPane.ERROR_MESSAGE);
     }
     else{  
      xmlproducto.cargarInformacionPedido(jCBProducto.getSelectedItem(),jTFNombre, jTFObservacion,jTFCantidad,jComboBox1,jCBSupermercado.getSelectedItem());
      this.nombrePro = jTFNombre.getText();
     }
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jCBSupermercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSupermercadoActionPerformed
        String[] idSuper = this.jCBSupermercado.getSelectedItem().toString().split(" ");
       
        if (!idSuper[0].equals("0")){
          jTFNombre.setEditable(false);
         
        }

        xmlproducto.cargarListaPedidoEnCombo(this.jCBProducto, jCBSupermercado.getSelectedItem(),false);
    }//GEN-LAST:event_jCBSupermercadoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
                   
    /**
     * @param args the command line arguments
     */
   private void initMyOwnComponents()
    {
        
           xmlsuper.cargarListaSuperEnCombo(jCBSupermercado,false);
           
           try{
           Comunicacion com = new Comunicacion();
          List <Pedido> lista = new ArrayList<Pedido>();
           lista =  com.devolverPedido();
            xmlproducto.borrarXMLPedido();  
           //System.out.println("LISTA:  "+ lista.get(0).getNombreProducto());
           xmlproducto.logralo(lista);
         
           }
           catch(Exception e){
                JOptionPane.showMessageDialog(null,"No hay conexion a webservice","Error", JOptionPane.ERROR_MESSAGE);
               
           }
           
//              Utilitaria.cargarListaAlmacenajeEnCombo(jCBAlmacenaje, false);
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManejoPedido().setVisible(true);
            }
        });
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox jCBProducto;
    private javax.swing.JComboBox jCBSupermercado;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLayeredPane jLPFondo;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLPvp;
    private javax.swing.JLabel jLSupermercado;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFObservacion;
    // End of variables declaration//GEN-END:variables
}
