/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearProducto.java
 *
 * Created on 24/04/2011, 12:32:08 PM
 */
package distribuidos.gui;
import distribuidos.datos.*;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.PrintWriter;

/**
 *
 * @author Administrador
 */
public class RegistroProducto extends javax.swing.JFrame {

    private ManejoXMLSupermercado xmlsucursal = new ManejoXMLSupermercado();
        
    private ManejoXMLProducto xmlproducto = new ManejoXMLProducto();
    public Util util = new Util();
    /** Creates new form CrearProducto */
    public RegistroProducto() {
        initComponents();
        xmlsucursal.cargarListaSuperEnCombo(this.jCBSucursal,false);
        this.setIconImage(new ImageIcon("src/Images/Icon.jpg").getImage());
    }
    
    public Util getUtil(){
        return this.util;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPFondo = new javax.swing.JLayeredPane();
        jLDescripcion = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jLCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jLPvp = new javax.swing.JLabel();
        jTFPrecio = new javax.swing.JTextField();
        jBbrowse = new javax.swing.JButton();
        jFCImagenProducto = new javax.swing.JFileChooser();
        jLImagen = new javax.swing.JLabel();
        jTFEstado = new javax.swing.JTextField();
        jLStrockMin = new javax.swing.JLabel();
        jLSucursal = new javax.swing.JLabel();
        jBAtras = new javax.swing.JButton();
        jCBSucursal = new javax.swing.JComboBox();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLImagenPro = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Producto");
        setResizable(false);

        jLPFondo.setBackground(new java.awt.Color(255, 255, 255));

        jLDescripcion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLDescripcion.setText("Descripcion:");
        jLDescripcion.setBounds(260, 60, 70, 20);
        jLPFondo.add(jLDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFDescripcion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescripcionActionPerformed(evt);
            }
        });
        jTFDescripcion.setBounds(360, 60, 150, 20);
        jLPFondo.add(jTFDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLCantidad.setText("Cantidad:");
        jLCantidad.setBounds(260, 120, 70, 20);
        jLPFondo.add(jLCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFCantidad.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantidadActionPerformed(evt);
            }
        });
        jTFCantidad.setBounds(360, 120, 150, 20);
        jLPFondo.add(jTFCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLPvp.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLPvp.setForeground(new java.awt.Color(255, 255, 255));
        jLPvp.setText("Precio:");
        jLPvp.setBounds(260, 150, 70, 20);
        jLPFondo.add(jLPvp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFPrecio.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecioActionPerformed(evt);
            }
        });
        jTFPrecio.setBounds(360, 150, 150, 20);
        jLPFondo.add(jTFPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBbrowse.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBbrowse.setText("Examinar");
        jBbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbrowseActionPerformed(evt);
            }
        });
        jBbrowse.setBounds(90, 220, 110, 23);
        jLPFondo.add(jBbrowse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jFCImagenProducto.setBounds(220, 390, 10, 10);
        jLPFondo.add(jFCImagenProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLImagen.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLImagen.setForeground(new java.awt.Color(255, 255, 255));
        jLImagen.setText("Imagen:");
        jLImagen.setBounds(20, 70, 70, 14);
        jLPFondo.add(jLImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFEstado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEstadoActionPerformed(evt);
            }
        });
        jTFEstado.setBounds(360, 90, 150, 20);
        jLPFondo.add(jTFEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLStrockMin.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLStrockMin.setForeground(new java.awt.Color(255, 255, 255));
        jLStrockMin.setText("Estado:");
        jLStrockMin.setBounds(260, 90, 90, 20);
        jLPFondo.add(jLStrockMin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLSucursal.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jLSucursal.setText("Sucursal:");
        jLSucursal.setBounds(20, 30, 70, 14);
        jLPFondo.add(jLSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBAtras.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBAtras.setText("Aceptar");
        jBAtras.setVerifyInputWhenFocusTarget(false);
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        jBAtras.setBounds(420, 310, 80, 20);
        jLPFondo.add(jBAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        jCBSucursal.setBounds(90, 30, 110, 20);
        jLPFondo.add(jCBSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre:");
        jLNombre.setBounds(260, 30, 60, 20);
        jLPFondo.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTFNombre.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.setBounds(360, 30, 150, 20);
        jLPFondo.add(jTFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLImagenPro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLImagenPro.setBounds(90, 70, 110, 130);
        jLPFondo.add(jLImagenPro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/561x571.jpg"))); // NOI18N
        jLFondo.setBounds(0, -230, 560, 570);
        jLPFondo.add(jLFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-554)/2, (screenSize.height-377)/2, 554, 377);
    }// </editor-fold>//GEN-END:initComponents
  
    private void jTFEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEstadoActionPerformed

    private void jTFDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescripcionActionPerformed

    private void jTFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantidadActionPerformed

    private void jTFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecioActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        // public agregarArchivo(String nombre, String descrip, String cantidad, String imagen, String costo, String estado) {

           XMLnodos xmlnodo = new XMLnodos();
           int var=0;
           int id =  jCBSucursal.getSelectedIndex()-1;
           String idS= Integer.toString(id);
           for (int i = 0; i < xmlnodo.cantNodos(); i++) {
            
               var=xmlnodo.cargaArchivos(i);
               Hilo Hilo,Hilo2;
               // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
             if(var==1){
                 //public Hilo(String ip_nodo_siguiente, int puerto_salida, int puerto_entrada, String opcion, String nombreProducto, String descripProducto, String cantidadProducto, String imagenProducto, String precioProducto, String estadoProducto) {
               
//           Hilo2 = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"enviarImagen","hola","chao","gh");
//           Hilo2.start();
               Hilo = new Hilo(DatosNodos.getIp_vecino(), DatosNodos.getPuerto_salida(),DatosNodos.getPuerto_entrada(),"crear", jTFNombre.getText(),jTFDescripcion.getText(),jTFCantidad.getText(),jLImagenPro.getText(),jTFPrecio.getText(),jTFEstado.getText(), idS);
               Hilo.start();
                           
               
             }
              

       // TODO add your handling code here:
        }
           
            xmlproducto.escribirProducto(jTFNombre.getText(),jTFDescripcion.getText(),jTFCantidad.getText(),jLImagenPro.getText(),jTFPrecio.getText(),jTFEstado.getText(),idS);
   this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jBbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbrowseActionPerformed
        // TODO add your handling code here:

        int returnVal = jFCImagenProducto.showOpenDialog(this);

        if (returnVal == jFCImagenProducto.APPROVE_OPTION) {
            File file = jFCImagenProducto.getSelectedFile();
            jLImagenPro.setIcon(new ImageIcon(file.getAbsolutePath()));
            jLImagenPro.setText(file.getPath());
            //HILO
            
        }else {
            System.out.println("");
        }
    }//GEN-LAST:event_jBbrowseActionPerformed
                   
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RegistroProducto().setVisible(true);
            }
        });
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBbrowse;
    private javax.swing.JComboBox jCBSucursal;
    private javax.swing.JFileChooser jFCImagenProducto;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLImagenPro;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLayeredPane jLPFondo;
    private javax.swing.JLabel jLPvp;
    private javax.swing.JLabel jLStrockMin;
    private javax.swing.JLabel jLSucursal;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPrecio;
    // End of variables declaration//GEN-END:variables
}
